apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onap-orchestrator-dev

bases:
- ../../base

nameSuffix: -dev

commonLabels:
  environment: development

replicas:
- name: orchestrator-api
  count: 1

images:
- name: onap-so-modern
  newTag: dev

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

configMapGenerator:
- name: orchestrator-config
  behavior: merge
  literals:
  - log-level=DEBUG
  - api-workers=2
